# Fast runner (trick from @y0ssar1an) (out-dated)
sudo: false

# Language of deployment
language: go

# Version
go:
 - 1.15.x

# Environment variables
env:
 - GO111MODULE=on

# Only clone the most recent commit
git:
 depth: 1

# Notifications off
notifications:
 email: false

# Run all scripts
script:
 - make test-travis

# After build success
after_success:
 - bash <(curl -s https://codecov.io/bash)